perfect_qdevice_cfg: &perfect_qdevice_cfg
  num_qubits: 4
  T1: 0
  T2: 0
  init_time: 0
  single_qubit_gate_time: 0
  two_qubit_gate_time: 0
  measure_time: 0
  single_qubit_gate_depolar_prob: 0.0
  two_qubit_gate_depolar_prob: 0.0
stacks:
- name: node_0
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_1
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_2
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_3
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_4
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_5
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_6
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_7
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_8
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_9
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_10
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_11
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_12
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_13
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_14
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_15
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_16
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_17
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_18
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_19
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_20
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_21
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_22
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_23
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_24
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_25
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_26
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_27
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_28
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_29
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_30
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_31
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_32
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_33
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_34
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_35
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_36
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_37
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_38
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_39
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_40
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_41
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_42
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_43
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_44
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_45
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_46
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_47
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_48
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_49
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
links:
- stack1: node_0
  stack2: node_1
  typ: perfect
- stack1: node_1
  stack2: node_2
  typ: perfect
- stack1: node_2
  stack2: node_3
  typ: perfect
- stack1: node_3
  stack2: node_4
  typ: perfect
- stack1: node_4
  stack2: node_5
  typ: perfect
- stack1: node_5
  stack2: node_6
  typ: perfect
- stack1: node_6
  stack2: node_7
  typ: perfect
- stack1: node_7
  stack2: node_8
  typ: perfect
- stack1: node_8
  stack2: node_9
  typ: perfect
- stack1: node_9
  stack2: node_10
  typ: perfect
- stack1: node_10
  stack2: node_11
  typ: perfect
- stack1: node_11
  stack2: node_12
  typ: perfect
- stack1: node_12
  stack2: node_13
  typ: perfect
- stack1: node_13
  stack2: node_14
  typ: perfect
- stack1: node_14
  stack2: node_15
  typ: perfect
- stack1: node_15
  stack2: node_16
  typ: perfect
- stack1: node_16
  stack2: node_17
  typ: perfect
- stack1: node_17
  stack2: node_18
  typ: perfect
- stack1: node_18
  stack2: node_19
  typ: perfect
- stack1: node_19
  stack2: node_20
  typ: perfect
- stack1: node_20
  stack2: node_21
  typ: perfect
- stack1: node_21
  stack2: node_22
  typ: perfect
- stack1: node_22
  stack2: node_23
  typ: perfect
- stack1: node_23
  stack2: node_24
  typ: perfect
- stack1: node_24
  stack2: node_25
  typ: perfect
- stack1: node_25
  stack2: node_26
  typ: perfect
- stack1: node_26
  stack2: node_27
  typ: perfect
- stack1: node_27
  stack2: node_28
  typ: perfect
- stack1: node_28
  stack2: node_29
  typ: perfect
- stack1: node_29
  stack2: node_30
  typ: perfect
- stack1: node_30
  stack2: node_31
  typ: perfect
- stack1: node_31
  stack2: node_32
  typ: perfect
- stack1: node_32
  stack2: node_33
  typ: perfect
- stack1: node_33
  stack2: node_34
  typ: perfect
- stack1: node_34
  stack2: node_35
  typ: perfect
- stack1: node_35
  stack2: node_36
  typ: perfect
- stack1: node_36
  stack2: node_37
  typ: perfect
- stack1: node_37
  stack2: node_38
  typ: perfect
- stack1: node_38
  stack2: node_39
  typ: perfect
- stack1: node_39
  stack2: node_40
  typ: perfect
- stack1: node_40
  stack2: node_41
  typ: perfect
- stack1: node_41
  stack2: node_42
  typ: perfect
- stack1: node_42
  stack2: node_43
  typ: perfect
- stack1: node_43
  stack2: node_44
  typ: perfect
- stack1: node_44
  stack2: node_45
  typ: perfect
- stack1: node_45
  stack2: node_46
  typ: perfect
- stack1: node_46
  stack2: node_47
  typ: perfect
- stack1: node_47
  stack2: node_48
  typ: perfect
- stack1: node_48
  stack2: node_49
  typ: perfect
- stack1: node_0
  stack2: node_49
  typ: perfect
- stack1: node_0
  stack2: node_2
  typ: perfect
- stack1: node_1
  stack2: node_3
  typ: perfect
- stack1: node_2
  stack2: node_4
  typ: perfect
- stack1: node_3
  stack2: node_5
  typ: perfect
- stack1: node_4
  stack2: node_6
  typ: perfect
- stack1: node_5
  stack2: node_7
  typ: perfect
- stack1: node_6
  stack2: node_8
  typ: perfect
- stack1: node_7
  stack2: node_9
  typ: perfect
- stack1: node_8
  stack2: node_10
  typ: perfect
- stack1: node_9
  stack2: node_11
  typ: perfect
- stack1: node_10
  stack2: node_12
  typ: perfect
- stack1: node_11
  stack2: node_13
  typ: perfect
- stack1: node_12
  stack2: node_14
  typ: perfect
- stack1: node_13
  stack2: node_15
  typ: perfect
- stack1: node_14
  stack2: node_16
  typ: perfect
- stack1: node_15
  stack2: node_17
  typ: perfect
- stack1: node_16
  stack2: node_18
  typ: perfect
- stack1: node_17
  stack2: node_19
  typ: perfect
- stack1: node_18
  stack2: node_20
  typ: perfect
- stack1: node_19
  stack2: node_21
  typ: perfect
- stack1: node_20
  stack2: node_22
  typ: perfect
- stack1: node_21
  stack2: node_23
  typ: perfect
- stack1: node_22
  stack2: node_24
  typ: perfect
- stack1: node_23
  stack2: node_25
  typ: perfect
- stack1: node_24
  stack2: node_26
  typ: perfect
- stack1: node_25
  stack2: node_27
  typ: perfect
- stack1: node_26
  stack2: node_28
  typ: perfect
- stack1: node_27
  stack2: node_29
  typ: perfect
- stack1: node_28
  stack2: node_30
  typ: perfect
- stack1: node_29
  stack2: node_31
  typ: perfect
- stack1: node_30
  stack2: node_32
  typ: perfect
- stack1: node_31
  stack2: node_33
  typ: perfect
- stack1: node_32
  stack2: node_34
  typ: perfect
- stack1: node_33
  stack2: node_35
  typ: perfect
- stack1: node_34
  stack2: node_36
  typ: perfect
- stack1: node_35
  stack2: node_37
  typ: perfect
- stack1: node_36
  stack2: node_38
  typ: perfect
- stack1: node_37
  stack2: node_39
  typ: perfect
- stack1: node_38
  stack2: node_40
  typ: perfect
- stack1: node_39
  stack2: node_41
  typ: perfect
- stack1: node_40
  stack2: node_42
  typ: perfect
- stack1: node_41
  stack2: node_43
  typ: perfect
- stack1: node_42
  stack2: node_44
  typ: perfect
- stack1: node_43
  stack2: node_45
  typ: perfect
- stack1: node_44
  stack2: node_46
  typ: perfect
- stack1: node_45
  stack2: node_47
  typ: perfect
- stack1: node_46
  stack2: node_48
  typ: perfect
- stack1: node_47
  stack2: node_49
  typ: perfect
- stack1: node_0
  stack2: node_48
  typ: perfect
- stack1: node_1
  stack2: node_49
  typ: perfect
- stack1: node_0
  stack2: node_26
  typ: perfect
- stack1: node_0
  stack2: node_35
  typ: perfect
- stack1: node_1
  stack2: node_22
  typ: perfect
- stack1: node_2
  stack2: node_47
  typ: perfect
- stack1: node_4
  stack2: node_25
  typ: perfect
- stack1: node_5
  stack2: node_41
  typ: perfect
- stack1: node_6
  stack2: node_42
  typ: perfect
- stack1: node_8
  stack2: node_23
  typ: perfect
- stack1: node_9
  stack2: node_38
  typ: perfect
- stack1: node_10
  stack2: node_35
  typ: perfect
- stack1: node_15
  stack2: node_24
  typ: perfect
- stack1: node_17
  stack2: node_36
  typ: perfect
- stack1: node_19
  stack2: node_39
  typ: perfect
- stack1: node_20
  stack2: node_45
  typ: perfect
- stack1: node_22
  stack2: node_34
  typ: perfect
- stack1: node_26
  stack2: node_44
  typ: perfect
- stack1: node_27
  stack2: node_49
  typ: perfect
- stack1: node_28
  stack2: node_47
  typ: perfect
- stack1: node_31
  stack2: node_45
  typ: perfect
- stack1: node_33
  stack2: node_48
  typ: perfect
- stack1: node_35
  stack2: node_49
  typ: perfect
- stack1: node_36
  stack2: node_47
  typ: perfect
- stack1: node_37
  stack2: node_45
  typ: perfect
- stack1: node_41
  stack2: node_48
  typ: perfect
- stack1: node_42
  stack2: node_49
  typ: perfect
clinks:
- stack1: node_0
  stack2: node_1
  typ: instant
- stack1: node_1
  stack2: node_2
  typ: instant
- stack1: node_2
  stack2: node_3
  typ: instant
- stack1: node_3
  stack2: node_4
  typ: instant
- stack1: node_4
  stack2: node_5
  typ: instant
- stack1: node_5
  stack2: node_6
  typ: instant
- stack1: node_6
  stack2: node_7
  typ: instant
- stack1: node_7
  stack2: node_8
  typ: instant
- stack1: node_8
  stack2: node_9
  typ: instant
- stack1: node_9
  stack2: node_10
  typ: instant
- stack1: node_10
  stack2: node_11
  typ: instant
- stack1: node_11
  stack2: node_12
  typ: instant
- stack1: node_12
  stack2: node_13
  typ: instant
- stack1: node_13
  stack2: node_14
  typ: instant
- stack1: node_14
  stack2: node_15
  typ: instant
- stack1: node_15
  stack2: node_16
  typ: instant
- stack1: node_16
  stack2: node_17
  typ: instant
- stack1: node_17
  stack2: node_18
  typ: instant
- stack1: node_18
  stack2: node_19
  typ: instant
- stack1: node_19
  stack2: node_20
  typ: instant
- stack1: node_20
  stack2: node_21
  typ: instant
- stack1: node_21
  stack2: node_22
  typ: instant
- stack1: node_22
  stack2: node_23
  typ: instant
- stack1: node_23
  stack2: node_24
  typ: instant
- stack1: node_24
  stack2: node_25
  typ: instant
- stack1: node_25
  stack2: node_26
  typ: instant
- stack1: node_26
  stack2: node_27
  typ: instant
- stack1: node_27
  stack2: node_28
  typ: instant
- stack1: node_28
  stack2: node_29
  typ: instant
- stack1: node_29
  stack2: node_30
  typ: instant
- stack1: node_30
  stack2: node_31
  typ: instant
- stack1: node_31
  stack2: node_32
  typ: instant
- stack1: node_32
  stack2: node_33
  typ: instant
- stack1: node_33
  stack2: node_34
  typ: instant
- stack1: node_34
  stack2: node_35
  typ: instant
- stack1: node_35
  stack2: node_36
  typ: instant
- stack1: node_36
  stack2: node_37
  typ: instant
- stack1: node_37
  stack2: node_38
  typ: instant
- stack1: node_38
  stack2: node_39
  typ: instant
- stack1: node_39
  stack2: node_40
  typ: instant
- stack1: node_40
  stack2: node_41
  typ: instant
- stack1: node_41
  stack2: node_42
  typ: instant
- stack1: node_42
  stack2: node_43
  typ: instant
- stack1: node_43
  stack2: node_44
  typ: instant
- stack1: node_44
  stack2: node_45
  typ: instant
- stack1: node_45
  stack2: node_46
  typ: instant
- stack1: node_46
  stack2: node_47
  typ: instant
- stack1: node_47
  stack2: node_48
  typ: instant
- stack1: node_48
  stack2: node_49
  typ: instant
- stack1: node_0
  stack2: node_49
  typ: instant
- stack1: node_0
  stack2: node_2
  typ: instant
- stack1: node_1
  stack2: node_3
  typ: instant
- stack1: node_2
  stack2: node_4
  typ: instant
- stack1: node_3
  stack2: node_5
  typ: instant
- stack1: node_4
  stack2: node_6
  typ: instant
- stack1: node_5
  stack2: node_7
  typ: instant
- stack1: node_6
  stack2: node_8
  typ: instant
- stack1: node_7
  stack2: node_9
  typ: instant
- stack1: node_8
  stack2: node_10
  typ: instant
- stack1: node_9
  stack2: node_11
  typ: instant
- stack1: node_10
  stack2: node_12
  typ: instant
- stack1: node_11
  stack2: node_13
  typ: instant
- stack1: node_12
  stack2: node_14
  typ: instant
- stack1: node_13
  stack2: node_15
  typ: instant
- stack1: node_14
  stack2: node_16
  typ: instant
- stack1: node_15
  stack2: node_17
  typ: instant
- stack1: node_16
  stack2: node_18
  typ: instant
- stack1: node_17
  stack2: node_19
  typ: instant
- stack1: node_18
  stack2: node_20
  typ: instant
- stack1: node_19
  stack2: node_21
  typ: instant
- stack1: node_20
  stack2: node_22
  typ: instant
- stack1: node_21
  stack2: node_23
  typ: instant
- stack1: node_22
  stack2: node_24
  typ: instant
- stack1: node_23
  stack2: node_25
  typ: instant
- stack1: node_24
  stack2: node_26
  typ: instant
- stack1: node_25
  stack2: node_27
  typ: instant
- stack1: node_26
  stack2: node_28
  typ: instant
- stack1: node_27
  stack2: node_29
  typ: instant
- stack1: node_28
  stack2: node_30
  typ: instant
- stack1: node_29
  stack2: node_31
  typ: instant
- stack1: node_30
  stack2: node_32
  typ: instant
- stack1: node_31
  stack2: node_33
  typ: instant
- stack1: node_32
  stack2: node_34
  typ: instant
- stack1: node_33
  stack2: node_35
  typ: instant
- stack1: node_34
  stack2: node_36
  typ: instant
- stack1: node_35
  stack2: node_37
  typ: instant
- stack1: node_36
  stack2: node_38
  typ: instant
- stack1: node_37
  stack2: node_39
  typ: instant
- stack1: node_38
  stack2: node_40
  typ: instant
- stack1: node_39
  stack2: node_41
  typ: instant
- stack1: node_40
  stack2: node_42
  typ: instant
- stack1: node_41
  stack2: node_43
  typ: instant
- stack1: node_42
  stack2: node_44
  typ: instant
- stack1: node_43
  stack2: node_45
  typ: instant
- stack1: node_44
  stack2: node_46
  typ: instant
- stack1: node_45
  stack2: node_47
  typ: instant
- stack1: node_46
  stack2: node_48
  typ: instant
- stack1: node_47
  stack2: node_49
  typ: instant
- stack1: node_0
  stack2: node_48
  typ: instant
- stack1: node_1
  stack2: node_49
  typ: instant
- stack1: node_0
  stack2: node_26
  typ: instant
- stack1: node_0
  stack2: node_35
  typ: instant
- stack1: node_1
  stack2: node_22
  typ: instant
- stack1: node_2
  stack2: node_47
  typ: instant
- stack1: node_4
  stack2: node_25
  typ: instant
- stack1: node_5
  stack2: node_41
  typ: instant
- stack1: node_6
  stack2: node_42
  typ: instant
- stack1: node_8
  stack2: node_23
  typ: instant
- stack1: node_9
  stack2: node_38
  typ: instant
- stack1: node_10
  stack2: node_35
  typ: instant
- stack1: node_15
  stack2: node_24
  typ: instant
- stack1: node_17
  stack2: node_36
  typ: instant
- stack1: node_19
  stack2: node_39
  typ: instant
- stack1: node_20
  stack2: node_45
  typ: instant
- stack1: node_22
  stack2: node_34
  typ: instant
- stack1: node_26
  stack2: node_44
  typ: instant
- stack1: node_27
  stack2: node_49
  typ: instant
- stack1: node_28
  stack2: node_47
  typ: instant
- stack1: node_31
  stack2: node_45
  typ: instant
- stack1: node_33
  stack2: node_48
  typ: instant
- stack1: node_35
  stack2: node_49
  typ: instant
- stack1: node_36
  stack2: node_47
  typ: instant
- stack1: node_37
  stack2: node_45
  typ: instant
- stack1: node_41
  stack2: node_48
  typ: instant
- stack1: node_42
  stack2: node_49
  typ: instant
