perfect_qdevice_cfg: &perfect_qdevice_cfg
  num_qubits: 4
  T1: 0
  T2: 0
  init_time: 0
  single_qubit_gate_time: 0
  two_qubit_gate_time: 0
  measure_time: 0
  single_qubit_gate_depolar_prob: 0.0
  two_qubit_gate_depolar_prob: 0.0
stacks:
- name: node_0
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_1
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_2
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_3
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_4
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_5
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_6
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_7
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_8
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_9
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_10
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_11
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_12
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_13
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_14
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_15
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_16
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_17
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_18
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_19
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_20
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_21
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_22
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_23
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
- name: node_24
  qdevice_typ: generic
  qdevice_cfg:
    <<: *perfect_qdevice_cfg
links:
- stack1: node_0
  stack2: node_1
  typ: perfect
- stack1: node_0
  stack2: node_2
  typ: perfect
- stack1: node_0
  stack2: node_14
  typ: perfect
- stack1: node_0
  stack2: node_23
  typ: perfect
- stack1: node_0
  stack2: node_24
  typ: perfect
- stack1: node_1
  stack2: node_2
  typ: perfect
- stack1: node_1
  stack2: node_3
  typ: perfect
- stack1: node_1
  stack2: node_19
  typ: perfect
- stack1: node_1
  stack2: node_24
  typ: perfect
- stack1: node_2
  stack2: node_3
  typ: perfect
- stack1: node_2
  stack2: node_4
  typ: perfect
- stack1: node_3
  stack2: node_4
  typ: perfect
- stack1: node_3
  stack2: node_5
  typ: perfect
- stack1: node_3
  stack2: node_19
  typ: perfect
- stack1: node_4
  stack2: node_5
  typ: perfect
- stack1: node_4
  stack2: node_6
  typ: perfect
- stack1: node_5
  stack2: node_7
  typ: perfect
- stack1: node_5
  stack2: node_23
  typ: perfect
- stack1: node_6
  stack2: node_7
  typ: perfect
- stack1: node_6
  stack2: node_8
  typ: perfect
- stack1: node_7
  stack2: node_9
  typ: perfect
- stack1: node_8
  stack2: node_9
  typ: perfect
- stack1: node_8
  stack2: node_10
  typ: perfect
- stack1: node_8
  stack2: node_23
  typ: perfect
- stack1: node_9
  stack2: node_10
  typ: perfect
- stack1: node_9
  stack2: node_11
  typ: perfect
- stack1: node_10
  stack2: node_11
  typ: perfect
- stack1: node_10
  stack2: node_12
  typ: perfect
- stack1: node_11
  stack2: node_12
  typ: perfect
- stack1: node_11
  stack2: node_13
  typ: perfect
- stack1: node_12
  stack2: node_13
  typ: perfect
- stack1: node_12
  stack2: node_14
  typ: perfect
- stack1: node_13
  stack2: node_14
  typ: perfect
- stack1: node_13
  stack2: node_15
  typ: perfect
- stack1: node_14
  stack2: node_16
  typ: perfect
- stack1: node_15
  stack2: node_16
  typ: perfect
- stack1: node_16
  stack2: node_17
  typ: perfect
- stack1: node_16
  stack2: node_18
  typ: perfect
- stack1: node_17
  stack2: node_18
  typ: perfect
- stack1: node_17
  stack2: node_19
  typ: perfect
- stack1: node_18
  stack2: node_19
  typ: perfect
- stack1: node_18
  stack2: node_20
  typ: perfect
- stack1: node_19
  stack2: node_20
  typ: perfect
- stack1: node_19
  stack2: node_21
  typ: perfect
- stack1: node_20
  stack2: node_21
  typ: perfect
- stack1: node_20
  stack2: node_22
  typ: perfect
- stack1: node_21
  stack2: node_22
  typ: perfect
- stack1: node_21
  stack2: node_23
  typ: perfect
- stack1: node_22
  stack2: node_23
  typ: perfect
- stack1: node_22
  stack2: node_24
  typ: perfect
clinks:
- stack1: node_0
  stack2: node_1
  typ: instant
- stack1: node_0
  stack2: node_2
  typ: instant
- stack1: node_0
  stack2: node_14
  typ: instant
- stack1: node_0
  stack2: node_23
  typ: instant
- stack1: node_0
  stack2: node_24
  typ: instant
- stack1: node_1
  stack2: node_2
  typ: instant
- stack1: node_1
  stack2: node_3
  typ: instant
- stack1: node_1
  stack2: node_19
  typ: instant
- stack1: node_1
  stack2: node_24
  typ: instant
- stack1: node_2
  stack2: node_3
  typ: instant
- stack1: node_2
  stack2: node_4
  typ: instant
- stack1: node_3
  stack2: node_4
  typ: instant
- stack1: node_3
  stack2: node_5
  typ: instant
- stack1: node_3
  stack2: node_19
  typ: instant
- stack1: node_4
  stack2: node_5
  typ: instant
- stack1: node_4
  stack2: node_6
  typ: instant
- stack1: node_5
  stack2: node_7
  typ: instant
- stack1: node_5
  stack2: node_23
  typ: instant
- stack1: node_6
  stack2: node_7
  typ: instant
- stack1: node_6
  stack2: node_8
  typ: instant
- stack1: node_7
  stack2: node_9
  typ: instant
- stack1: node_8
  stack2: node_9
  typ: instant
- stack1: node_8
  stack2: node_10
  typ: instant
- stack1: node_8
  stack2: node_23
  typ: instant
- stack1: node_9
  stack2: node_10
  typ: instant
- stack1: node_9
  stack2: node_11
  typ: instant
- stack1: node_10
  stack2: node_11
  typ: instant
- stack1: node_10
  stack2: node_12
  typ: instant
- stack1: node_11
  stack2: node_12
  typ: instant
- stack1: node_11
  stack2: node_13
  typ: instant
- stack1: node_12
  stack2: node_13
  typ: instant
- stack1: node_12
  stack2: node_14
  typ: instant
- stack1: node_13
  stack2: node_14
  typ: instant
- stack1: node_13
  stack2: node_15
  typ: instant
- stack1: node_14
  stack2: node_16
  typ: instant
- stack1: node_15
  stack2: node_16
  typ: instant
- stack1: node_16
  stack2: node_17
  typ: instant
- stack1: node_16
  stack2: node_18
  typ: instant
- stack1: node_17
  stack2: node_18
  typ: instant
- stack1: node_17
  stack2: node_19
  typ: instant
- stack1: node_18
  stack2: node_19
  typ: instant
- stack1: node_18
  stack2: node_20
  typ: instant
- stack1: node_19
  stack2: node_20
  typ: instant
- stack1: node_19
  stack2: node_21
  typ: instant
- stack1: node_20
  stack2: node_21
  typ: instant
- stack1: node_20
  stack2: node_22
  typ: instant
- stack1: node_21
  stack2: node_22
  typ: instant
- stack1: node_21
  stack2: node_23
  typ: instant
- stack1: node_22
  stack2: node_23
  typ: instant
- stack1: node_22
  stack2: node_24
  typ: instant
