noisy_qdevice_cfg: &noisy_qdevice_cfg
  num_qubits: 4
  T1: 500000000
  T2: 500000000
  init_time: 10000
  single_qubit_gate_time: 10000
  two_qubit_gate_time: 10000
  measure_time: 10000
  single_qubit_gate_depolar_prob: 0.5
  two_qubit_gate_depolar_prob: 0.5
stacks:
- name: node_0
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
- name: node_1
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
- name: node_2
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
- name: node_3
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
- name: node_4
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
- name: node_5
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
- name: node_6
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
- name: node_7
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
- name: node_8
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
- name: node_9
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
- name: node_10
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
- name: node_11
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
- name: node_12
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
- name: node_13
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
- name: node_14
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
- name: node_15
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
- name: node_16
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
- name: node_17
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
- name: node_18
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
- name: node_19
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
- name: node_20
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
- name: node_21
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
- name: node_22
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
- name: node_23
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
- name: node_24
  qdevice_typ: generic
  qdevice_cfg:
    <<: *noisy_qdevice_cfg
link_cfg: &link_cfg
  fidelity: 0.97
  prob_success: 0.2
  length: 10
links:
- stack1: node_0
  stack2: node_1
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_0
  stack2: node_2
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_0
  stack2: node_14
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_0
  stack2: node_23
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_0
  stack2: node_24
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_1
  stack2: node_2
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_1
  stack2: node_3
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_1
  stack2: node_19
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_1
  stack2: node_24
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_2
  stack2: node_3
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_2
  stack2: node_4
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_3
  stack2: node_4
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_3
  stack2: node_5
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_3
  stack2: node_19
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_4
  stack2: node_5
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_4
  stack2: node_6
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_5
  stack2: node_7
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_5
  stack2: node_23
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_6
  stack2: node_7
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_6
  stack2: node_8
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_7
  stack2: node_9
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_8
  stack2: node_9
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_8
  stack2: node_10
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_8
  stack2: node_23
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_9
  stack2: node_10
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_9
  stack2: node_11
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_10
  stack2: node_11
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_10
  stack2: node_12
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_11
  stack2: node_12
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_11
  stack2: node_13
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_12
  stack2: node_13
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_12
  stack2: node_14
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_13
  stack2: node_14
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_13
  stack2: node_15
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_14
  stack2: node_16
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_15
  stack2: node_16
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_16
  stack2: node_17
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_16
  stack2: node_18
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_17
  stack2: node_18
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_17
  stack2: node_19
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_18
  stack2: node_19
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_18
  stack2: node_20
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_19
  stack2: node_20
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_19
  stack2: node_21
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_20
  stack2: node_21
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_20
  stack2: node_22
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_21
  stack2: node_22
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_21
  stack2: node_23
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_22
  stack2: node_23
  typ: depolarise
  cfg:
    <<: *link_cfg
- stack1: node_22
  stack2: node_24
  typ: depolarise
  cfg:
    <<: *link_cfg
clinks:
- stack1: node_0
  stack2: node_1
  typ: default
  cfg:
    length: 10
- stack1: node_0
  stack2: node_2
  typ: default
  cfg:
    length: 10
- stack1: node_0
  stack2: node_14
  typ: default
  cfg:
    length: 10
- stack1: node_0
  stack2: node_23
  typ: default
  cfg:
    length: 10
- stack1: node_0
  stack2: node_24
  typ: default
  cfg:
    length: 10
- stack1: node_1
  stack2: node_2
  typ: default
  cfg:
    length: 10
- stack1: node_1
  stack2: node_3
  typ: default
  cfg:
    length: 10
- stack1: node_1
  stack2: node_19
  typ: default
  cfg:
    length: 10
- stack1: node_1
  stack2: node_24
  typ: default
  cfg:
    length: 10
- stack1: node_2
  stack2: node_3
  typ: default
  cfg:
    length: 10
- stack1: node_2
  stack2: node_4
  typ: default
  cfg:
    length: 10
- stack1: node_3
  stack2: node_4
  typ: default
  cfg:
    length: 10
- stack1: node_3
  stack2: node_5
  typ: default
  cfg:
    length: 10
- stack1: node_3
  stack2: node_19
  typ: default
  cfg:
    length: 10
- stack1: node_4
  stack2: node_5
  typ: default
  cfg:
    length: 10
- stack1: node_4
  stack2: node_6
  typ: default
  cfg:
    length: 10
- stack1: node_5
  stack2: node_7
  typ: default
  cfg:
    length: 10
- stack1: node_5
  stack2: node_23
  typ: default
  cfg:
    length: 10
- stack1: node_6
  stack2: node_7
  typ: default
  cfg:
    length: 10
- stack1: node_6
  stack2: node_8
  typ: default
  cfg:
    length: 10
- stack1: node_7
  stack2: node_9
  typ: default
  cfg:
    length: 10
- stack1: node_8
  stack2: node_9
  typ: default
  cfg:
    length: 10
- stack1: node_8
  stack2: node_10
  typ: default
  cfg:
    length: 10
- stack1: node_8
  stack2: node_23
  typ: default
  cfg:
    length: 10
- stack1: node_9
  stack2: node_10
  typ: default
  cfg:
    length: 10
- stack1: node_9
  stack2: node_11
  typ: default
  cfg:
    length: 10
- stack1: node_10
  stack2: node_11
  typ: default
  cfg:
    length: 10
- stack1: node_10
  stack2: node_12
  typ: default
  cfg:
    length: 10
- stack1: node_11
  stack2: node_12
  typ: default
  cfg:
    length: 10
- stack1: node_11
  stack2: node_13
  typ: default
  cfg:
    length: 10
- stack1: node_12
  stack2: node_13
  typ: default
  cfg:
    length: 10
- stack1: node_12
  stack2: node_14
  typ: default
  cfg:
    length: 10
- stack1: node_13
  stack2: node_14
  typ: default
  cfg:
    length: 10
- stack1: node_13
  stack2: node_15
  typ: default
  cfg:
    length: 10
- stack1: node_14
  stack2: node_16
  typ: default
  cfg:
    length: 10
- stack1: node_15
  stack2: node_16
  typ: default
  cfg:
    length: 10
- stack1: node_16
  stack2: node_17
  typ: default
  cfg:
    length: 10
- stack1: node_16
  stack2: node_18
  typ: default
  cfg:
    length: 10
- stack1: node_17
  stack2: node_18
  typ: default
  cfg:
    length: 10
- stack1: node_17
  stack2: node_19
  typ: default
  cfg:
    length: 10
- stack1: node_18
  stack2: node_19
  typ: default
  cfg:
    length: 10
- stack1: node_18
  stack2: node_20
  typ: default
  cfg:
    length: 10
- stack1: node_19
  stack2: node_20
  typ: default
  cfg:
    length: 10
- stack1: node_19
  stack2: node_21
  typ: default
  cfg:
    length: 10
- stack1: node_20
  stack2: node_21
  typ: default
  cfg:
    length: 10
- stack1: node_20
  stack2: node_22
  typ: default
  cfg:
    length: 10
- stack1: node_21
  stack2: node_22
  typ: default
  cfg:
    length: 10
- stack1: node_21
  stack2: node_23
  typ: default
  cfg:
    length: 10
- stack1: node_22
  stack2: node_23
  typ: default
  cfg:
    length: 10
- stack1: node_22
  stack2: node_24
  typ: default
  cfg:
    length: 10
